# This workflow will install badger dependencies, lint with flake8, and run the test suite, for all combinations
# of operating systems and version numbers specified in the matrix

name: Build Status

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:
    if: ${{ github.repository == 'YektaY/Badger' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9, 3.11]
    env:
      DISPLAY: ':99.0'
      QT_MAC_WANTS_LAYER: 1  # PyQT gui tests involving qtbot interaction on macOS will fail without this

    steps:
    - uses: actions/checkout@v3
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: badger-env
        environment-file: environment-dev.yml
    - name: Install python packages
      shell: bash -el {0}
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          mamba install flake8 zipp 
          mamba install --file requirements.txt --file windows-dev-requirements.txt
        else
          mamba install flake8 zipp $(cat requirements.txt)
        fi
    - name: Install xopt 
      shell: bash -el {0}
      run: |
          pip install --user xopt
    - name: Install pyqt5
      shell: bash -el {0}
      run: |
          pip install PyQt5
    - name: Install Badger
      shell: bash -el {0}
      run: |
          pip install .
    - name: Test with pytest
      shell: bash -el {0}
      run: |
          python run_tests.py 

